[package]
name = "klister"
version = "0.0.1"
edition = "2021"

[dependencies]
as-any = "0.3.1"
duct = "0.13.7"
dyn-clone = "1.0.17"
gc = { version = "0.5", features = ["derive"] }
libffi = "3.2.0"
num-bigint = "0.4"
num-traits = "0.2"
once_cell = "1.19.0"
regex = "1.10.4"
serde_json = "1.0.116"
